"use client";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Row=Record<string,unknown>; type View="home"|"sales"|"inventory"|"clients"|"cash"|"more";
const money=(v:unknown)=>`$${Number(v||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const val=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));

export default function MobileOffice({userName,signOut}:{userName:string;signOut:string}){
 const [data,setData]=useState<Record<string,Row[]>>({}),[view,setView]=useState<View>("home"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modal,setModal]=useState<string|null>(null),[search,setSearch]=useState("");
 const load=useCallback(async()=>{setLoading(true);const r=await fetch("/api/mobile");const j=await r.json();if(!r.ok)setError(j.error||"No se pudo cargar");else{setData(j);setError("")}setLoading(false)},[]);useEffect(()=>{load()},[load]);
 const post=async(action:string,payload:Row)=>{setError("");const r=await fetch("/api/mobile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,data:payload})}),j=await r.json();if(!r.ok){setError(j.error||"No se pudo guardar");return j}setModal(null);await load();return j};
 const products=data.products||[],balances=data.balances||[],team=data.team||[],clients=data.clients||[],invoices=data.invoices||[],cash=data.cash||[],suppliers=data.suppliers||[],purchases=data.purchases||[],calculations=data.calculations||[],protocols=data.protocols||[];
 const stock=(id:unknown)=>balances.filter(x=>x.product_id===id).reduce((s,x)=>s+Number(x.quantity||0),0),cashTotal=cash.reduce((s,x)=>s+(x.type==="Ingreso"?1:x.type==="Egreso"?-1:0)*Number(x.amount||0),0),pending=invoices.reduce((s,x)=>s+Number(x.balance||0),0);
 const filtered=products.filter(p=>`${p.name} ${p.concentration}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="mobile-office"><header className="mobile-top"><div className="mobile-logo"><Image src="/peptibra-logo-original.png" width={1774} height={887} alt="Peptibra Peptide Depot" priority/><span>GESTIÓN MÓVIL</span></div><div className="mobile-account"><span>{userName.split(" ")[0]}</span><a href={signOut}>Salir</a></div></header>
  {error&&<div className="mobile-error">{error}<button onClick={()=>setError("")}>×</button></div>}
  <section className="mobile-content">
   {loading?<div className="mobile-loading"><i/><p>Actualizando datos…</p></div>:view==="home"?<Home/>:view==="sales"?<Sales/>:view==="inventory"?<Inventory/>:view==="clients"?<Clients/>:view==="cash"?<Cash/>:<More/>}
  </section><nav className="mobile-nav">{([['home','⌂','Inicio'],['sales','▤','Ventas'],['inventory','◇','Stock'],['clients','♙','Clientes'],['cash','$','Caja'],['more','•••','Más']] as [View,string,string][]).map(([id,icon,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i><span>{label}</span></button>)}</nav>
  {modal&&<Modal title={modal} close={()=>setModal(null)}>{modal==="Nuevo producto"?<ProductForm/>:modal==="Nuevo cliente"?<ClientForm/>:modal==="Nueva factura"?<InvoiceForm/>:modal==="Movimiento de caja"?<CashForm/>:modal==="Integrante del equipo"?<TeamForm/>:modal==="Proveedor"?<SupplierForm/>:modal==="Compra"?<PurchaseForm/>:modal==="Cálculo"?<CalculationForm/>:<ProtocolForm/>}</Modal>}
 </main>;

 function Home(){return <><div className="mobile-greeting"><span>OFICINA PRIVADA</span><h1>Hola, {userName.split(" ")[0]}</h1><p>Así va Peptibra ahora mismo.</p></div><div className="mobile-metrics"><Card label="Disponible en caja" value={money(cashTotal)} tone="green"/><Card label="Por cobrar" value={money(pending)} tone="amber"/><Card label="Productos" value={String(products.length)} tone="blue"/><Card label="Unidades" value={String(products.reduce((s,p)=>s+stock(p.id),0))}/></div><h2 className="mobile-section-title">Acciones rápidas</h2><div className="quick-grid"><Quick icon="＋" label="Factura" action={()=>setModal("Nueva factura")}/><Quick icon="⇄" label="Movimiento" action={()=>setModal("Movimiento de caja")}/><Quick icon="◇" label="Producto" action={()=>setModal("Nuevo producto")}/><Quick icon="♙" label="Cliente" action={()=>setModal("Nuevo cliente")}/></div><ListTitle title="Facturas recientes" action={()=>setView("sales")}/><div className="mobile-list">{invoices.slice(0,5).map(i=><article key={String(i.id)}><div><b>{String(i.number)}</b><span>{String(i.client_name)}</span></div><div className="right"><b>{money(i.total)}</b><em className={String(i.status).toLowerCase()}>{String(i.status)}</em></div></article>)}</div></>}
 function Sales(){return <><PageHead eyebrow="OPERACIONES" title="Ventas y facturas" action="+ Factura" onAction={()=>setModal("Nueva factura")}/><div className="mobile-list roomy">{invoices.map(i=><article key={String(i.id)}><div><b>{String(i.number)}</b><span>{String(i.client_name)} · {String(i.seller_name)}</span><small>{String(i.created_at).slice(0,10)}</small></div><div className="right"><b>{money(i.total)}</b><em className={String(i.status).toLowerCase()}>{String(i.status)}</em>{Number(i.balance)>0&&<button className="mini" onClick={()=>pay(i)}>Cobrar</button>}</div></article>)}</div></>}
 function Inventory(){return <><PageHead eyebrow="PRODUCTOS" title="Inventario" action="+ Producto" onAction={()=>setModal("Nuevo producto")}/><label className="mobile-search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto"/></label><div className="product-mobile-grid">{filtered.map(p=>{const qty=stock(p.id);return <article key={String(p.id)}><i>{String(p.name).slice(0,2)}</i><div><b>{String(p.name)}</b><span>{String(p.concentration)}</span><strong>{money(p.normal_price||p.price)}</strong></div><aside><b className={qty<0?"negative":qty<=Number(p.reorder_point)?"low":""}>{qty}</b><span>unidades</span><div><button onClick={()=>adjust(p,-1)}>−</button><button onClick={()=>adjust(p,1)}>+</button></div></aside></article>})}</div></>}
 function Clients(){return <><PageHead eyebrow="RELACIONES" title="Clientes" action="+ Cliente" onAction={()=>setModal("Nuevo cliente")}/><div className="mobile-list roomy">{clients.map(c=><article key={String(c.id)}><i className="avatar">{String(c.first_name).slice(0,1)}</i><div><b>{String(c.first_name)} {String(c.last_name)}</b><span>{String(c.code)} · {String(c.phone||"Sin teléfono")}</span></div></article>)}</div></>}
 function Cash(){return <><PageHead eyebrow="FINANZAS" title="Caja" action="+ Movimiento" onAction={()=>setModal("Movimiento de caja")}/><div className="cash-hero"><span>Disponible en caja</span><b>{money(cashTotal)}</b><small>Todos los movimientos están expresados en USD</small></div><div className="mobile-list roomy">{cash.map(m=><article key={String(m.id)}><i className={m.type==="Ingreso"?"cash-in":"cash-out"}>{m.type==="Ingreso"?"↓":"↑"}</i><div><b>{String(m.category)}</b><span>{String(m.notes||m.partner_name||"")}</span></div><div className="right"><b className={m.type==="Ingreso"?"green":""}>{m.type==="Ingreso"?"+":"−"}{money(m.amount)}</b><small>{String(m.created_at).slice(0,10)}</small></div></article>)}</div></>}
 function More(){return <><PageHead eyebrow="HERRAMIENTAS" title="Más módulos"/><div className="more-grid"><Module title="Equipo" count={team.length} action={()=>setModal("Integrante del equipo")}/><Module title="Proveedores" count={suppliers.length} action={()=>setModal("Proveedor")}/><Module title="Compras" count={purchases.length} action={()=>setModal("Compra")}/><Module title="Calculadora" count={calculations.length} action={()=>setModal("Cálculo")}/><Module title="Protocolos" count={protocols.length} action={()=>setModal("Protocolo")}/><Module title="Configuración" count={0} action={()=>post("saveSetting",{key:"last_mobile_access",value:new Date().toISOString()})}/></div><ListTitle title="Equipo"/><div className="mobile-list">{team.map(t=><article key={String(t.id)}><div><b>{String(t.name)}</b><span>{String(t.role)}{t.partner_name?` · ${String(t.partner_name)}`:""}</span></div><div className="right"><b>{Number(t.commission).toFixed(1)}%</b><small>comisión</small></div></article>)}</div></>}
 async function adjust(p:Row,change:number){await post("adjustStock",{productId:p.id,location:"GENERAL",change,reason:"Ajuste desde móvil"})}
 async function pay(i:Row){const original=prompt(`Saldo US${money(i.balance)}. Monto recibido:`);if(!original)return;const currency=confirm("¿El pago fue en pesos dominicanos?")?"DOP":"USD",rate=currency==="DOP"?Number(prompt("Tasa DOP/USD:","60")||60):1,usd=Number(original)/rate,excess=Math.max(0,usd-Number(i.balance)),excessAction=excess>.005?(confirm(`Sobran US${money(excess)}. Aceptar = dejar en caja; Cancelar = devolver.`)?"Caja":"Devolución"):"";await post("applyPayment",{invoiceId:i.id,originalAmount:Number(original),currency,exchangeRate:rate,excessAction,method:"Efectivo"})}
 function submit(action:string){return (e:FormEvent<HTMLFormElement>)=>{e.preventDefault();post(action,val(e.currentTarget))}}
 function ProductForm(){return <form onSubmit={submit("createProduct")} className="mobile-form"><Field name="name" label="Nombre" required/><Field name="sku" label="Código / SKU" required/><Field name="concentration" label="Concentración o volumen"/><Field name="description" label="Descripción"/><div className="form-pair"><Field name="unitCost" label="Costo" type="number"/><Field name="normalPrice" label="Precio" type="number"/></div><div className="form-pair"><Field name="bacPrice" label="Precio + agua BAC" type="number"/><Field name="stock" label="Inventario inicial" type="number"/></div><button>Guardar producto</button></form>}
 function ClientForm(){return <form onSubmit={submit("saveClient")} className="mobile-form"><Field name="firstName" label="Nombre" required/><Field name="lastName" label="Apellido"/><Field name="phone" label="Teléfono"/><button>Guardar cliente</button></form>}
 function InvoiceForm(){const [cart,setCart]=useState<Row[]>([]),[product,setProduct]=useState("");const selected=products.find(p=>String(p.id)===product);return <form onSubmit={e=>{e.preventDefault();const f=val(e.currentTarget);post("createInvoice",{...f,items:cart})}} className="mobile-form"><Select name="clientId" label="Cliente" items={clients} render={x=>`${x.code} · ${x.first_name} ${x.last_name}`}/><Select name="sellerId" label="Vendedor / socio" items={team} render={x=>String(x.name)}/><div className="cart-add"><select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Producto</option>{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)} {String(p.concentration)}</option>)}</select><button type="button" onClick={()=>selected&&setCart([...cart,{productId:selected.id,quantity:1,unitPrice:selected.normal_price||selected.price,unitCost:selected.unit_cost||0,name:selected.name}])}>Agregar</button></div>{cart.map((x,n)=><div className="cart-row" key={n}><span>{String(x.name)}</span><input type="number" min="1" value={Number(x.quantity)} onChange={e=>setCart(cart.map((y,k)=>k===n?{...y,quantity:Number(e.target.value)}:y))}/><b>{money(Number(x.quantity)*Number(x.unitPrice))}</b><button type="button" onClick={()=>setCart(cart.filter((_,k)=>k!==n))}>×</button></div>)}<Field name="discount" label="Descuento total" type="number"/><Field name="notes" label="Notas"/><button disabled={!cart.length}>Crear factura</button></form>}
 function CashForm(){return <form onSubmit={submit("cashMovement")} className="mobile-form"><label>Movimiento<select name="type"><option>Ingreso</option><option>Egreso</option><option>No monetario</option></select></label><Field name="category" label="Motivo" required/><Field name="amount" label="Monto USD" type="number" required/><Select name="partnerId" label="Socio (opcional)" items={team.filter(t=>t.role==="Socio")} render={x=>String(x.name)} optional/><Field name="notes" label="Notas"/><button>Registrar movimiento</button></form>}
 function TeamForm(){return <form onSubmit={submit("saveTeam")} className="mobile-form"><Field name="name" label="Nombre" required/><Field name="phone" label="Teléfono"/><label>Categoría<select name="role"><option>Vendedor</option><option>Socio</option></select></label><Select name="partnerId" label="Socio responsable" items={team.filter(t=>t.role==="Socio")} render={x=>String(x.name)} optional/><div className="form-pair"><Field name="commission" label="Comisión %" type="number"/><Field name="maxDiscount" label="Descuento máximo %" type="number"/></div><button>Guardar integrante</button></form>}
 function SupplierForm(){return <form onSubmit={submit("saveSupplier")} className="mobile-form"><Field name="name" label="Proveedor" required/><Field name="phone" label="Teléfono"/><Field name="notes" label="Notas"/><button>Guardar proveedor</button></form>}
 function PurchaseForm(){return <form onSubmit={submit("savePurchase")} className="mobile-form"><Select name="supplierId" label="Proveedor" items={suppliers} render={x=>String(x.name)}/><Field name="concept" label="Concepto" required/><label>Tipo<select name="type"><option>Inventario / insumos</option><option>Gasto operativo</option></select></label><div className="form-pair"><Field name="total" label="Total" type="number"/><Field name="paid" label="Pagado" type="number"/></div><button>Guardar compra</button></form>}
 function CalculationForm(){return <form onSubmit={submit("saveCalculation")} className="mobile-form"><Field name="name" label="Nombre" required/><div className="form-pair"><Field name="productCost" label="Producto" type="number"/><Field name="shipping" label="Envío" type="number"/></div><div className="form-pair"><Field name="labelCost" label="Etiqueta" type="number"/><Field name="packaging" label="Empaque" type="number"/></div><div className="form-pair"><Field name="bacCost" label="Agua BAC" type="number"/><Field name="otherCost" label="Otros" type="number"/></div><div className="form-pair"><Field name="units" label="Unidades" type="number"/><Field name="salePrice" label="Precio venta" type="number"/></div><button>Guardar cálculo</button></form>}
 function ProtocolForm(){return <form onSubmit={submit("saveProtocol")} className="mobile-form"><Select name="productId" label="Producto" items={products} render={x=>`${x.name} ${x.concentration}`}/><Field name="name" label="Nombre del protocolo" required/><div className="form-pair"><Field name="vialMg" label="Vial mg" type="number"/><Field name="diluentMl" label="Agua mL" type="number"/></div><div className="form-pair"><Field name="dose" label="Dosis" type="number"/><Field name="everyDays" label="Cada días" type="number"/></div><Field name="weeks" label="Semanas" type="number"/><button>Guardar protocolo</button></form>}
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="mobile-modal-bg" onMouseDown={close}><section className="mobile-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>NUEVO REGISTRO</span><h2>{title}</h2></div><button onClick={close}>×</button></header>{children}</section></div>}
function Card({label,value,tone=""}:{label:string;value:string;tone?:string}){return <article className={`metric ${tone}`}><span>{label}</span><b>{value}</b></article>}
function Quick({icon,label,action}:{icon:string;label:string;action:()=>void}){return <button onClick={action}><i>{icon}</i><span>{label}</span></button>}
function PageHead({eyebrow,title,action,onAction}:{eyebrow:string;title:string;action?:string;onAction?:()=>void}){return <div className="mobile-page-head"><div><span>{eyebrow}</span><h1>{title}</h1></div>{action&&<button onClick={onAction}>{action}</button>}</div>}
function ListTitle({title,action}:{title:string;action?:()=>void}){return <div className="list-title"><h2>{title}</h2>{action&&<button onClick={action}>Ver todo</button>}</div>}
function Module({title,count,action}:{title:string;count:number;action:()=>void}){return <button onClick={action}><i>{title.slice(0,1)}</i><b>{title}</b><span>{count?`${count} registros`:"Abrir"}</span></button>}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} step={type==="number"?"any":undefined} required={required}/></label>}
function Select({name,label,items,render,optional=false}:{name:string;label:string;items:Row[];render:(x:Row)=>string;optional?:boolean}){return <label>{label}<select name={name} required={!optional}><option value="">{optional?"Ninguno":"Seleccionar"}</option>{items.map(x=><option key={String(x.id)} value={String(x.id)}>{render(x)}</option>)}</select></label>}

