import { getAuthorizedUser } from "@/app/chatgpt-auth";
import { cloudDb } from "@/lib/cloudflare/supabase-compat";

const tables=["calculations","products","product_profiles","inventory_balances","inventory_movements","team","clients","invoices","invoice_items","payments","cash_movements","suppliers","purchases","supplier_payments","protocols","internal_withdrawals","internal_withdrawal_payments","legacy_sales","app_settings"];
const cloud=()=>cloudDb;

export async function GET(){const user=await getAuthorizedUser();if(user?.role!=="admin")return Response.json({error:"Solo el administrador puede exportar respaldos"},{status:403});try{const s=cloud(),entries=await Promise.all(tables.map(async table=>{const {data,error}=await s.from(table).select("*");if(error)throw error;return[table,data||[]]}));return Response.json({format:"PEPTIBRA-CLOUD-BACKUP",version:1,createdAt:new Date().toISOString(),tables:Object.fromEntries(entries)},{headers:{"content-disposition":`attachment; filename="Peptibra-Web-${new Date().toISOString().slice(0,10)}.json"`}})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo exportar"},{status:500})}}

export async function POST(request:Request){const user=await getAuthorizedUser();if(user?.role!=="admin")return Response.json({error:"Solo el administrador puede restaurar respaldos"},{status:403});try{const body=await request.json();if(body?.format!=="PEPTIBRA-CLOUD-BACKUP"||!body.tables)return Response.json({error:"El archivo no es un respaldo válido"},{status:400});const s=cloud();for(const table of tables){const rows=body.tables[table];if(!Array.isArray(rows)||!rows.length)continue;const conflict=table==="product_profiles"?"product_id":table==="inventory_balances"?"product_id,location":table==="app_settings"?"key":"id";const {error}=await s.from(table).upsert(rows,{onConflict:conflict});if(error)throw error}const now=new Date().toISOString();await s.from("app_settings").upsert({key:"mobile_data_revision",value:now,updated_at:now},{onConflict:"key"});return Response.json({ok:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo restaurar"},{status:500})}}
