"use client";
import {createContext,useContext,useEffect,useState} from "react";
type Locale="en"|"es";
const Context=createContext<{locale:Locale;setLocale:(v:Locale)=>void}>({locale:"en",setLocale:()=>{}});

const pairs:[string,string][]=[
  ["Catálogo","Catalog"],["Nuestro modelo","Our model"],["Contacto","Contact"],["Acceso privado","Private access"],
  ["EL LOTE COMO PUNTO DE PARTIDA","BUILT AROUND THE BATCH"],["Un hub especializado","A specialized hub"],["en péptidos de investigación.","for research peptides."],
  ["Descubre una selección respaldada por información de lote, documentación analítica y una visión clara de la disponibilidad.","Explore a curated selection supported by batch information, analytical documentation, and clear availability status."],
  ["Explorar catálogo →","Explore catalog →"],["Explorar catálogo","Explore catalog"],["Consultar COAs","View COAs"],["Conoce","Learn"],["cómo funciona nuestro modelo","how our model works"],["o revisa las","or review the"],["preguntas frecuentes","frequently asked questions"],
  ["Última verificación de lote","Latest batch verification"],["LOTE PB2601 · ANÁLISIS INDEPENDIENTE","BATCH PB2601 · INDEPENDENT ANALYSIS"],["PUREZA HPLC","HPLC PURITY"],["PRODUCTOS INICIALES","CATALOG PRODUCTS"],
  ["Identidad confirmada mediante espectrometría de masas","Identity confirmed by mass spectrometry"],["Sin sustancias no declaradas en los lotes analizados","No undeclared substances in analyzed batches"],["Reportes publicados y vinculados al inventario","Published reports linked to inventory"],["● Verificación independiente · sin vínculos financieros","● Independent verification · no financial ties"],
  ["SELECCIÓN PEPTIBRA","PEPTIBRA SELECTION"],["Cada lote cuenta","Every batch tells"],["una historia verificable.","a verifiable story."],["Presentación, disponibilidad y respaldo analítico conviven en una misma experiencia para que la información importante siempre esté al alcance.","Presentation, availability, and analytical support come together in one experience, keeping essential information within reach."],
  ["CATÁLOGO PEPTIBRA","PEPTIBRA CATALOG"],["Información para decidir con criterio.","Information for informed decisions."],["Abrir catálogo →","Open catalog →"],
  ["Polvo liofilizado","Lyophilized powder"],["Polvo liofilizado azul marino","Navy-blue lyophilized powder"],["Tapa","Cap"],["Gris","Gray"],["Verde","Green"],["Roja","Red"],["Negra","Black"],["Marrón","Brown"],["Tapa Gris","Gray cap"],["Tapa Verde","Green cap"],["Tapa Roja","Red cap"],["Tapa Negra","Black cap"],["Tapa Marrón","Brown cap"],["Documentación disponible","Documentation available"],["Documentación en revisión","Documentation under review"],
  ["Selección curada","Curated selection"],["Una red de fuentes evaluadas amplía la disponibilidad sin perder consistencia.","A network of vetted sources broadens availability while maintaining consistency."],["Documentación asociada","Linked documentation"],["La evidencia analítica acompaña al producto y al lote que representa.","Analytical evidence accompanies the product and the batch it represents."],["Actualización continua","Continuous updates"],["La información evoluciona junto con el inventario y sus nuevos reportes.","Information evolves alongside inventory and new reports."],
  ["PEPTIBRA EVOLUCIONA","PEPTIBRA EVOLVES"],["Una experiencia cada vez más completa.","An increasingly complete experience."],["Estamos preparando una forma segura y transparente de adquirir productos directamente desde Peptibra, con disponibilidad actualizada y documentación vinculada a cada lote.","We are preparing a secure and transparent way to purchase products directly through Peptibra, with current availability and documentation linked to every batch."],["Conocer la selección","View the selection"],
  ["Un catálogo claro y documentado.","A clear, documented catalog."],["¿Peptibra fabrica los productos?","Does Peptibra manufacture the products?"],["Peptibra funciona como un hub especializado que consolida inventario y documentación de distintos suplidores seleccionados.","Peptibra operates as a specialized hub that consolidates inventory and documentation from selected suppliers."],["¿Dónde encuentro el COA?","Where can I find the COA?"],["Los certificados se organizan por producto y lote, según la documentación disponible del suplidor correspondiente.","Certificates are organized by product and batch, based on documentation available from the corresponding supplier."],["¿Puedo comprar desde la página?","Can I purchase through the website?"],["La compra directa todavía no está habilitada. Próximamente Peptibra incorporará una experiencia de adquisición integrada al catálogo.","Direct purchasing is not yet available. Peptibra will soon introduce a purchasing experience integrated with the catalog."],["Consultar todas las preguntas →","View all questions →"],
  ["Productos destinados exclusivamente a fines de investigación. No aptos para consumo humano.","Products intended exclusively for research purposes. Not for human consumption."],
  ["EXCLUSIVAMENTE PARA USO DE INVESTIGACIÓN. NO APTO PARA USO HUMANO.","FOR RESEARCH USE ONLY. NOT FOR HUMAN USE."],
  ["Descargo de responsabilidad de la FDA:","FDA Disclaimer:"],
  ["El contenido y los productos mencionados en este sitio web no han sido evaluados por la Administración de Alimentos y Medicamentos de los Estados Unidos (FDA). Estos productos no están destinados a diagnosticar, tratar, curar ni prevenir ninguna enfermedad. Todos los productos se venden exclusivamente para fines de investigación, laboratorio o análisis y están destinados al uso controlado en investigación de laboratorio. La información proporcionada es estrictamente para fines informativos.","The content and products mentioned on this website have not been evaluated by the U.S. Food and Drug Administration (FDA). These products are not intended to diagnose, treat, cure, or prevent any disease. All products are sold exclusively for research, laboratory, or analytical purposes and are intended for controlled laboratory research use. The information provided is strictly for informational purposes only."],
  ["Todos los productos se venden únicamente para fines de investigación, laboratorio o análisis y están destinados al uso controlado en investigación de laboratorio.","All products are sold for research, laboratory, or analytical purposes only and are intended for controlled laboratory research use."],
  ["Peptibra es un proveedor de productos químicos. Peptibra no es una farmacia de preparación ni una instalación de preparación química según lo definido en la Sección 503A de la Ley Federal de Alimentos, Medicamentos y Cosméticos. Peptibra no es una instalación de externalización según lo definido en la Sección 503B de la Ley Federal de Alimentos, Medicamentos y Cosméticos. Las declaraciones realizadas en este sitio web no han sido evaluadas por la Administración de Alimentos y Medicamentos de los Estados Unidos. Los productos que ofrecemos no están destinados a diagnosticar, tratar, curar ni prevenir ninguna enfermedad. Exclusivamente para uso experimental in vitro en laboratorio.","Peptibra is a chemical supplier. Peptibra is not a compounding pharmacy or chemical compounding facility as defined under Section 503A of the Federal Food, Drug, and Cosmetic Act. Peptibra is not an outsourcing facility as defined under Section 503B of the Federal Food, Drug, and Cosmetic Act. The statements made within this website have not been evaluated by the U.S. Food and Drug Administration. The products we offer are not intended to diagnose, treat, cure, or prevent any disease. For laboratory in vitro experimental use only."],
  ["Copyright © 2026 Peptibra","Copyright © 2026 Peptibra"],
  ["Inicio / Catálogo","Home / Catalog"],["Catálogo de péptidos","Peptide catalog"],["Una selección dinámica con información de lote, disponibilidad y respaldo analítico en un solo lugar.","A dynamic selection with batch information, availability, and analytical support in one place."],["Documentación que acompaña cada lote.","Documentation that follows every batch."],
  ["Disponibilidad","Availability"],["Todos","All"],["Ordenar","Sort"],["Selección Peptibra","Peptibra selection"],["Nombre A–Z","Name A–Z"],["Presentación","Presentation"],["Buscar producto, categoría o presentación...","Search by product, category, or presentation..."],["Buscar productos","Search products"],["Filtrar por categoría","Filter by category"],["Restablecer filtros","Reset filters"],["producto","product"],["productos","products"],["Ver ficha →","View details →"],["Consultar","Inquire"],["No encontramos coincidencias.","No matches found."],["Prueba otra búsqueda o restablece los filtros.","Try another search or reset the filters."],["Ver todo el catálogo","View full catalog"],["Catálogo informativo para fines de investigación.","Informational catalog for research purposes."],["Solicitar información","Request information"],["Solicitar información →","Request information →"],
  ["Inicio","Home"],["Ruta de navegación","Breadcrumb"],["Formato","Format"],["Identificación","Identification"],["Documentación","Documentation"],["Cómo interpretar los COAs","How to interpret COAs"],["Exclusivamente para investigación in vitro y uso controlado de laboratorio. No apto para consumo humano o veterinario.","Exclusively for in vitro research and controlled laboratory use. Not for human or veterinary use."],["ÁREAS DE CONSULTA","RESEARCH AREAS"],["Contexto de investigación","Research context"],["TRAZABILIDAD","TRACEABILITY"],["Documentación por lote","Batch documentation"],["Peptibra organiza la evidencia disponible junto al producto que representa. Solicita el lote vigente para consultar su documentación específica.","Peptibra organizes available evidence alongside the product it represents. Request the current batch to review its specific documentation."],["Consultar lote vigente →","Request current batch →"],["← Volver al catálogo completo","← Return to full catalog"],
  ["CENTRO DE INFORMACIÓN","INFORMATION CENTER"],["Preguntas frecuentes","Frequently asked questions"],["Respuestas claras sobre el modelo de Peptibra, la documentación analítica y la forma correcta de interpretar nuestro catálogo.","Clear answers about Peptibra's model, analytical documentation, and the proper way to interpret our catalog."],["Contactar a Peptibra","Contact Peptibra"],["EN ESTA PÁGINA","ON THIS PAGE"],["Peptibra y su catálogo","Peptibra and its catalog"],["¿Qué es Peptibra?","What is Peptibra?"],["Peptibra es un hub especializado en péptidos de investigación. Reúne en un mismo catálogo información de productos, disponibilidad y documentación analítica procedente de suplidores seleccionados.","Peptibra is a specialized research peptide hub. It brings product information, availability, and analytical documentation from selected suppliers into one catalog."],
  ["¿Peptibra fabrica los productos publicados?","Does Peptibra manufacture the listed products?"],["No necesariamente. El modelo de Peptibra integra inventario de distintas fuentes evaluadas. En cada entrada buscamos mantener identificados el producto, su presentación, el lote y la documentación que corresponde al suplidor disponible.","Not necessarily. Peptibra's model integrates inventory from different vetted sources. Each listing identifies the product, presentation, batch, and documentation associated with the available supplier."],["¿Para qué uso están destinados los productos?","What are the products intended for?"],["Los productos del catálogo están destinados exclusivamente a investigación in vitro, análisis y trabajo controlado de laboratorio. No son medicamentos, no están destinados al consumo humano o veterinario y Peptibra no ofrece orientación de dosificación o uso clínico.","Catalog products are intended exclusively for in vitro research, analysis, and controlled laboratory work. They are not medicines, are not intended for human or veterinary consumption, and Peptibra does not provide dosing or clinical-use guidance."],
  ["COAs y evidencia analítica","COAs and analytical evidence"],["¿Cómo puedo consultar un COA?","How can I review a COA?"],["Los certificados de análisis se organizan por producto y lote. Cuando el documento está disponible, Peptibra lo vincula con la entrada correspondiente para que pueda revisarse junto con la información del inventario.","Certificates of analysis are organized by product and batch. When available, Peptibra links the document to the corresponding listing so it can be reviewed alongside inventory information."],["¿Cómo verifico que un COA corresponde al producto publicado?","How do I verify that a COA matches the listed product?"],["Compara el nombre del compuesto, número de lote, presentación, fecha del análisis y laboratorio emisor. Cuando existe una página de verificación externa, Peptibra procura incluir el enlace directo para facilitar la trazabilidad.","Compare the compound name, batch number, presentation, analysis date, and issuing laboratory. When an external verification page exists, Peptibra aims to include a direct link for traceability."],
  ["¿Qué indica una prueba de pureza HPLC?","What does an HPLC purity test indicate?"],["La cromatografía HPLC separa los componentes detectables de una muestra y permite estimar la proporción atribuida al compuesto principal. El resultado describe la muestra o lote analizado; no demuestra esterilidad, seguridad clínica, dosificación ni idoneidad para uso humano.","HPLC chromatography separates detectable components in a sample and estimates the proportion attributed to the primary compound. The result describes the analyzed sample or batch; it does not establish sterility, clinical safety, dosing, or suitability for human use."],["¿Todos los productos tienen pruebas de esterilidad, endotoxinas o metales pesados?","Are all products tested for sterility, endotoxins, or heavy metals?"],["No se presume ninguna prueba que no esté expresamente documentada. Esos análisis pueden formar parte de controles de laboratorio más amplios, pero Peptibra solo comunica los resultados que aparecen en la documentación específica del producto o lote.","No test is assumed unless expressly documented. These analyses may be part of broader laboratory controls, but Peptibra only communicates results shown in product- or batch-specific documentation."],["¿Un COA convierte el producto en un medicamento aprobado?","Does a COA make the product an approved medicine?"],["No. Un COA aporta resultados analíticos sobre una muestra determinada. No constituye aprobación regulatoria, evaluación médica ni evidencia para diagnóstico, tratamiento, prevención o consumo.","No. A COA provides analytical results for a specific sample. It is not regulatory approval, a medical evaluation, or evidence for diagnosis, treatment, prevention, or consumption."],
  ["Disponibilidad y soporte","Availability and support"],["¿La disponibilidad del catálogo se actualiza?","Is catalog availability updated?"],["Sí. La disponibilidad puede variar según el inventario de Peptibra y de sus suplidores. El catálogo se actualiza conforme se incorporan nuevos lotes, presentaciones y documentos.","Yes. Availability may vary based on Peptibra and supplier inventory. The catalog is updated as new batches, presentations, and documents are added."],["¿Puedo comprar directamente desde la página?","Can I purchase directly through the website?"],["Todavía no. Peptibra funciona actualmente como catálogo informativo y centro de consulta. Estamos preparando una experiencia de adquisición segura, con disponibilidad actualizada y documentación asociada a cada lote.","Not yet. Peptibra currently operates as an informational catalog and inquiry center. We are preparing a secure purchasing experience with current availability and batch-linked documentation."],["¿Cómo solicito información sobre un producto o documento?","How do I request information about a product or document?"],["Escríbenos a peptibra@gmail.com e indica el nombre del producto y, si aplica, el número de lote. Esto nos permite responder con la información más pertinente.","Email peptibra@gmail.com with the product name and, when applicable, the batch number. This helps us provide the most relevant information."],["¿NECESITAS MÁS INFORMACIÓN?","NEED MORE INFORMATION?"],["Conversemos sobre tu consulta.","Let's discuss your inquiry."],["Indica el producto o lote de interés para ayudarte con mayor precisión.","Include the product or batch of interest so we can assist you more precisely."],["Escribir a Peptibra →","Email Peptibra →"],
  ["Verificación de investigador","Researcher verification"],["El acceso está restringido a investigadores y laboratorios cualificados para uso in vitro y de laboratorio. Confirma los siguientes datos antes de continuar.","Access is restricted to qualified researchers and laboratories for in vitro and laboratory use. Please confirm the following before continuing."],["¿Qué tipo de investigador eres?","What type of researcher are you?"],["Selecciona tu perfil...","Select your profile..."],["Investigador independiente","Independent researcher"],["Laboratorio o institución","Laboratory or institution"],["Investigador académico","Academic researcher"],["Profesional cualificado","Qualified professional"],["Confirmo que tengo al menos 21 años.","I confirm that I am at least 21 years old."],["Confirmo que soy un investigador cualificado y que adquiriré productos exclusivamente para investigación in vitro o de laboratorio; nunca para uso humano o veterinario.","I confirm that I am a qualified researcher and will acquire products exclusively for in vitro or laboratory research, never for human or veterinary use."],["He leído y acepto los","I have read and accept the"],["Términos de venta","Terms of Sale"],["y la","and the"],["Política de privacidad","Privacy Policy"],["Entrar al sitio","Enter site"],["Salir — No cumplo los requisitos","Leave — I do not qualify"],["Declaración Peptibra · Acceso para investigación","Peptibra attestation · Research access"],
  ["Resumen","Overview"],["Productos","Products"],["Inventario","Inventory"],["Clientes","Customers"],["Actividad","Activity"],["Cerrar sesión","Sign out"],["PEPTIBRA · OPERACIONES","PEPTIBRA · OPERATIONS"],["+ Agregar producto","+ Add product"],["UNIDADES DISPONIBLES","AVAILABLE UNITS"],["En","Across"],["VALOR DEL INVENTARIO","INVENTORY VALUE"],["Precio × existencias","Price × stock"],["STOCK BAJO","LOW STOCK"],["Requieren atención","Require attention"],["Todo en orden","All clear"],["Control de existencias en tiempo real","Real-time inventory control"],["PRODUCTO","PRODUCT"],["CATEGORÍA","CATEGORY"],["PRECIO","PRICE"],["AJUSTE","ADJUSTMENT"],["mín.","min."],["Cargando inventario…","Loading inventory…"],["Tu inventario está listo para comenzar.","Your inventory is ready to begin."],["Agrega el primer producto para activar las métricas.","Add the first product to activate metrics."],["NUEVO PRODUCTO","NEW PRODUCT"],["Agregar al inventario","Add to inventory"],["Nombre","Name"],["Categoría","Category"],["Concentración","Concentration"],["Precio","Price"],["Stock inicial","Initial stock"],["Punto de reorden","Reorder point"],["Guardar producto","Save product"],["Péptido","Peptide"],["Accesorio","Accessory"],
  ["Blend de investigación presentado en vial para consulta técnica y evaluación documental por lote.","Research blend presented in a vial for technical review and batch-level documentation assessment."],["Péptido de investigación metabólica organizado con información de presentación y respaldo documental.","Metabolic research peptide organized with presentation information and documentary support."],["Péptido de cobre para investigación, presentado con su coloración característica y trazabilidad documental.","Copper peptide for research, presented with its characteristic color and traceable documentation."],["Compuesto de investigación metabólica incluido para consulta de presentación, disponibilidad y documentación.","Metabolic research compound listed for presentation, availability, and documentation review."],["Compuesto para investigación de triple receptor, presentado como parte del catálogo documentado de Peptibra.","Triple-receptor research compound presented as part of Peptibra's documented catalog."],
  ["Investigación de señalización celular","Cell-signaling research"],["Evaluación analítica de blends","Analytical blend evaluation"],["Consulta de composición por lote","Batch composition review"],["Investigación metabólica in vitro","In vitro metabolic research"],["Señalización mitocondrial","Mitochondrial signaling"],["Caracterización analítica","Analytical characterization"],["Investigación de péptidos de cobre","Copper-peptide research"],["Caracterización de muestras","Sample characterization"],["Evaluación de identidad y pureza","Identity and purity assessment"],["Investigación de receptores in vitro","In vitro receptor research"],["Consulta documental por lote","Batch documentation review"],["Investigación multirreceptor in vitro","In vitro multi-receptor research"],["Evaluación de identidad","Identity assessment"],["Revisión de documentación analítica","Analytical documentation review"],
  ["SOPORTE PEPTIBRA","PEPTIBRA SUPPORT"],["¿Cómo podemos ayudarte?","How can we help?"],["Contáctanos para solicitar información sobre productos, documentación específica por lote, COAs, disponibilidad del catálogo o consultas generales de cuentas de investigación.","Contact us for product information, batch-specific documentation, COAs, catalog availability, or general research account questions."],["Visitar FAQ","Visit FAQ"],
  ["TIEMPO DE RESPUESTA","RESPONSE TIME"],["Horario de atención","Support hours"],["Normalmente respondemos dentro de 24 horas y, por lo general, más rápido cuando estamos en línea.","We typically reply within 24 hours, and usually faster when we are online."],["Lunes–viernes","Monday–Friday"],["Sábado","Saturday"],["Domingos y feriados","Sunday & holidays"],["Cerrado","Closed"],
  ["CONTACTO DIRECTO","DIRECT CONTACT"],["Escríbele a Peptibra","Email Peptibra"],["Para recibir una respuesta más rápida, incluye el nombre del producto y el número de lote cuando estén disponibles.","For the fastest response, include the product name and batch number when available."],["ANTES DE ESCRIBIR","BEFORE YOU WRITE"],["Recursos de documentación","Documentation resources"],["Es posible que ya encuentres respuestas sobre COAs, pruebas, disponibilidad y uso exclusivo para investigación.","Quick answers about COAs, testing, availability, and research-only use may already be available."],["Revisar preguntas frecuentes →","Review frequently asked questions →"],
  ["FORMULARIO DE CONTACTO","CONTACT FORM"],["Envíanos un mensaje.","Send us a message."],["Normalmente respondemos dentro de 24 horas durante el horario de atención.","We typically reply within 24 hours during support hours."],["Tu nombre","Your name"],["¿En qué podemos ayudarte?","What can we help with?"],["Selecciona un tema","Select a topic"],["Información de producto","Product information"],["Documentación de lote o COA","Batch documentation or COA"],["Disponibilidad del catálogo","Catalog availability"],["Cuenta de investigación","Research account"],["Otra consulta","Other inquiry"],["Referencia de producto o lote","Product or batch reference"],["Opcional","Optional"],["Mensaje","Message"],["Cuéntanos cómo podemos ayudarte...","Tell us how we can help..."],["Entiendo que Peptibra proporciona productos y documentación exclusivamente para uso de investigación.","I understand Peptibra provides products and documentation exclusively for research use."],["Enviando...","Sending..."],["Enviar mensaje →","Send message →"],["Gracias. Tu mensaje ha sido enviado a Peptibra.","Thank you. Your message has been sent to Peptibra."],["No fue posible enviar tu mensaje.","Unable to send your message."]
];
const esToEn=Object.fromEntries(pairs),enToEs=Object.fromEntries(pairs.map(([es,en])=>[en,es]));
function swap(value:string,locale:Locale){const trimmed=value.trim(),next=(locale==="en"?esToEn:enToEs)[trimmed];if(next)return value.replace(trimmed,next);if(locale==="en")return value.replace("Ver ficha de ","View details for ").replace("Vial Peptibra ","Peptibra vial ").replace("Peptibra inicio","Peptibra home");return value.replace("View details for ","Ver ficha de ").replace("Peptibra vial ","Vial Peptibra ").replace("Peptibra home","Peptibra inicio")}
function translate(locale:Locale){
  document.documentElement.lang=locale;
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node:Node|null;
  while((node=walker.nextNode())){if(!node.parentElement?.closest("script,style")){const current=node.nodeValue||"",next=swap(current,locale);if(next!==current)node.nodeValue=next}}
  document.querySelectorAll<HTMLElement>("[placeholder],[aria-label],[title]").forEach(el=>["placeholder","aria-label","title"].forEach(a=>{const v=el.getAttribute(a);if(v){const next=swap(v,locale);if(next!==v)el.setAttribute(a,next)}}));
}
export function LanguageProvider({children}:{children:React.ReactNode}){
  const [locale,setState]=useState<Locale>("en");
  const setLocale=(v:Locale)=>{setState(v);localStorage.setItem("peptibra_language",v)};
  useEffect(()=>{const v=localStorage.getItem("peptibra_language");if(v==="es"||v==="en")setState(v)},[]);
  useEffect(()=>{translate(locale);const o=new MutationObserver(()=>translate(locale));o.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>o.disconnect()},[locale]);
  return <Context.Provider value={{locale,setLocale}}>{children}</Context.Provider>;
}
export function LanguageSwitcher({compact=false}:{compact?:boolean}){const {locale,setLocale}=useContext(Context);return <label className={`language-switcher${compact?" compact":""}`}><span>{locale==="en"?"Language":"Idioma"}</span><select aria-label="Language selector" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">English</option><option value="es">Español</option></select></label>}
