import Image from "next/image";
import Link from "next/link";
import VerificationGate from "./VerificationGate";
import SiteHeader from "./SiteHeader";
import HomeCatalog from "./HomeCatalog";

export default function Home(){return <main className="pb-site pb-public-new"><VerificationGate/><SiteHeader/>
  <section className="new-hero">
    <div><span className="new-eyebrow">PEPTIBRA · PEPTIDE DEPOT</span><h1>Research,<br/><em>clearly presented.</em></h1><p>Productos de investigación, presentaciones disponibles y documentación por lote.</p><div className="new-actions"><Link href="/products">Ver catálogo</Link><Link href="/coas">Consultar COAs</Link></div></div>
    <div className="new-hero-mark"><Image src="/peptibra-isotipo.png" width={700} height={700} alt="Peptibra" priority/><span>PEPTIBRA</span><b>Peptide Depot</b></div>
  </section>
  <section className="new-catalog-preview" id="catalogo"><header><div><span>SELECCIÓN PEPTIBRA</span><h2>Productos disponibles.</h2></div><Link href="/products">Explorar todo →</Link></header><HomeCatalog/></section>
  <section className="new-coa-strip" id="coas"><div><span>DOCUMENTACIÓN</span><h2>COAs organizados<br/>por producto y lote.</h2></div><p>Consulta el estado de la documentación disponible y solicita el reporte correspondiente al lote de interés.</p><Link href="/coas">Abrir centro de COAs →</Link></section>
  <section className="new-faq-preview"><span>FAQ</span><h2>Respuestas directas.</h2><div><details><summary>¿Cómo consulto un COA?</summary><p>Busca el producto en el centro de COAs y solicita la documentación del lote vigente.</p></details><details><summary>¿Qué presentaciones están disponibles?</summary><p>En el catálogo encontrarás las presentaciones disponibles para cada producto.</p></details><details><summary>¿Cómo hago una solicitud?</summary><p>Añade los productos al carrito y continúa la conversación por WhatsApp.</p></details></div><Link href="/faq">Ver todas las preguntas →</Link></section>
  <footer className="new-footer"><Image src="/peptibra-logo-dark.png" width={1774} height={887} alt="Peptibra" unoptimized/><nav><Link href="/products">Catálogo</Link><Link href="/coas">COAs</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contacto</Link></nav><a href="mailto:peptibra@gmail.com">peptibra@gmail.com</a></footer>
  <section className="pb-legal-disclaimer" aria-label="Research use disclaimer"><div><strong>FOR RESEARCH USE ONLY. NOT FOR HUMAN USE.</strong><p><b>FDA Disclaimer:</b> The content and products mentioned on this website have not been evaluated by the U.S. Food and Drug Administration (FDA). These products are not intended to diagnose, treat, cure, or prevent any disease. All products are sold exclusively for research, laboratory, or analytical purposes and are intended for controlled laboratory research use. The information provided is strictly for informational purposes only.</p><p>All products are sold for research, laboratory, or analytical purposes only and are intended for controlled laboratory research use.</p><p>Peptibra is a chemical supplier. Peptibra is not a compounding pharmacy or chemical compounding facility as defined under Section 503A of the Federal Food, Drug, and Cosmetic Act. Peptibra is not an outsourcing facility as defined under Section 503B of the Federal Food, Drug, and Cosmetic Act. The statements made within this website have not been evaluated by the U.S. Food and Drug Administration. The products we offer are not intended to diagnose, treat, cure, or prevent any disease. For laboratory in vitro experimental use only.</p><small>Copyright © 2026 Peptibra</small></div></section>
</main>}
